language: node_js
node_js:
  - "node"

# command to install dependencies
install:
  # Install Python requirements.
  - pip install --user -r requirements.txt
  # Install Curation Tool Javascript libraries.
  - cd curation-tool; npm install; cd ..
  # Download FaCT++ reasoner native libraries and use them.
  - wget -O - https://storage.googleapis.com/google-code-archive-downloads/v2/code.google.com/factplusplus/FaCTpp-linux-v1.5.2.tgz | tar zxf - --strip-components=2 -C jphyloref/lib "FaCT++-linux-v1.5.2/64bit/libFaCTPlusPlusJNI.so"
  - export JVM_ARGS="-Djava.library.path=jphyloref/lib/"
  - export JPHYLOREF_ARGS="--reasoner fact++"

# command to run tests
script:
  - cd phyx2owl; python -m pytest; cd ..
  - travis_wait 40 py.test ./tests --durations=0
